"""fix_created_at_timezone

Revision ID: 6254d7cdd6d7
Revises: 
Create Date: 2026-10-08 23:35:15.266924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6254d7cdd6d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('last_seen_in_bot', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('last_vacancy_check', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('liked', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('disliked', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.create_table('filters_hh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['tg_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filters_hh_tg_id'), 'filters_hh', ['tg_id'], unique=True)
    op.create_table('users_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('vacancy_id', sa.String(length=124), nullable=False),
    sa.Column('vacancy_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('viewed', sa.Boolean(), server_default='False', nullable=False),
    sa.ForeignKeyConstraint(['tg_id'], ['users.tg_id'], name='fk_user_notification_tg_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vacancy_id')
    )
    op.create_table('vacancy_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.String(length=50), nullable=False),
    sa.Column('action', sa.Enum('LIKE', 'SKIP', 'VIEWED', name='actiontype'), nullable=False),
    sa.Column('vacancy_title', sa.String(length=255), nullable=True),
    sa.Column('vacancy_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.tg_id'], name='fk_vacancy_action_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'vacancy_id', name='uq_user_vacancy_action')
    )
    op.create_index(op.f('ix_vacancy_actions_user_id'), 'vacancy_actions', ['user_id'], unique=False)
    op.create_index(op.f('ix_vacancy_actions_vacancy_id'), 'vacancy_actions', ['vacancy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_actions_vacancy_id'), table_name='vacancy_actions')
    op.drop_index(op.f('ix_vacancy_actions_user_id'), table_name='vacancy_actions')
    op.drop_table('vacancy_actions')
    op.drop_table('users_notification')
    op.drop_index(op.f('ix_filters_hh_tg_id'), table_name='filters_hh')
    op.drop_table('filters_hh')
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
