"""добавлена возможность пометить что юзер просто просмотрел вакансию, но никак не взаимодействовал

Revision ID: fb6ec8fc5ee6
Revises: 6bdbb0b59f93
Create Date: 2026-08-07 04:06:02.559129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb6ec8fc5ee6'
down_revision: Union[str, Sequence[str], None] = '6bdbb0b59f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Используем batch_alter_table с recreate='always' для SQLite
    with op.batch_alter_table('vacancy_actions', recreate='always') as batch_op:
        # Меняем тип колонки action на Enum
        batch_op.alter_column(
            'action',
            existing_type=sa.VARCHAR(length=4),
            type_=sa.Enum('LIKE', 'SKIP', 'VIEWED', name='actiontype'),
            existing_nullable=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'vacancy_actions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('vacancy_actions', 'action',
               existing_type=sa.Enum('LIKE', 'SKIP', 'VIEWED', name='actiontype'),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)
    # ### end Alembic commands ###
